USE minors_2022;

DROP TABLE IF EXISTS starter_minors_fantasy;

CREATE TABLE starter_minors_fantasy (
  player_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) DEFAULT NULL,
  last_name VARCHAR(100) DEFAULT NULL,
  ORG VARCHAR(100) DEFAULT NULL,
  ETA INT DEFAULT NULL,
  ERA DECIMAL(4.2),
  IP DECIMAL(4,1),
  WHIP DECIMAL(3.2),
  H9 DECIMAL(3,1),
  BB9 DECIMAL(3,1),
  K9 DECIMAL(3,1),
  HR9 DECIMAL(3,1)
  
);
